---
repos:
  - repo: local
    hooks:

      - id: stylua
        name: StyLua code formatter
        description: An opinionated Lua code formatter
        entry: stylua
        language: system
        types: [file]
        files: ^(.*\.lua|\.luacheckrc|\.busted)$

      - id: luacheck
        name: Luacheck diagnostics
        description: Runs luacheck for linting and static analysis using the system installation. This acts as a 'second pair of eyes' just in case LuaLS misses something.
        entry: luacheck
        language: system
        pass_filenames: true
        types:
          - lua

      - id: lua-language-server
        name: LuaLS diagnostics
        description: Runs type checks and other diagnostics using the system installation of lua-language-server.
        entry: lua-language-server --check=. --checklevel=Information
        language: system
        pass_filenames: false
        types:
          - lua

      - id: tests
        name: Tests
        description: Runs existing unit and golden tests.
        entry: ./test.lua
        language: system
        pass_filenames: false
        types:
          - lua

      - id: coverage
        name: Test coverage
        description: Fails if test coverage is less than 100%.
        entry: ./ci-coverage.lua
        language: system
        pass_filenames: false
        types:
          - lua
